---
# Source: quay-operator/templates/policy-quay-operator-install.yaml
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-quay-operator-install
  namespace: open-cluster-policies
spec:
  clusterSets:
    - hub
    - managed
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
# Source: quay-operator/templates/policy-quay-operator-install.yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-quay-operator-install
  namespace: open-cluster-policies
placementRef:
  name: placement-policy-quay-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-quay-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
# Source: quay-operator/templates/policy-quay-operator-install.yaml
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-quay-operator-install
  namespace: open-cluster-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-operator-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: quay-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator-quay
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: quay-operator
            namespace: quay-operator
          subscription:
            name: quay-operator
            namespace: quay-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            channel: stable-3.9
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-operator-status
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: quay-operator
                spec:
                  displayName: 'Red Hat Quay'
                status:
                  phase: Succeeded
