# NOTE: this is used by PolicyGenerator and not by kuztomize directly

# TODO: Can we get rid of this somehow? right now does not seem to be a way to set ClusterSet with policygenerator?

apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-quay
  namespace: policies-autoshift # TODO: since this is not being rendered by kustomzie, but buy policygenerator, need to specify the namespace here becasue it is not picking it up from kustomize or policygenerator
spec:
  # TODO - make this dynamic
  clusterSets:
    - hub
    - managed
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: "autoshift.io/quay"
              operator: In
              values:
                - "true"
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
