apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-devspaces-operator-uninstall
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator-devspaces
        spec:
          remediationAction: enforce
          severity: high
          complianceType: mustnothave
          operatorGroup:
            name: {{ .Values.devspaces.namespace }}
            namespace: {{ .Values.devspaces.namespace }}
          subscription:
            namespace: {{ .Values.devspaces.namespace }}
            channel: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/dev-spaces-channel" | default "{{ .Values.devspaces.channel }}" hub{{ "}}" }}'
            name: {{ .Values.devspaces.name }}
            source: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/dev-spaces-source" | default "{{ .Values.devspaces.source }}" hub{{ "}}" }}'
            sourceNamespace: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/dev-spaces-source-namespace" | default "{{ .Values.devspaces.sourceNamespace }}" hub{{ "}}" }}'
          # Getting Label and then capitalizing first letter
          upgradeApproval: '{{ "{{hub" }} $upgrade_approval := index .ManagedClusterLabels "autoshift.io/dev-spaces-install-plan-approval" | default "{{ .Values.devspaces.installPlanApproval }}" {{ "-hub}}" }} {{ "{{hub" }} print (substr 0 1 $upgrade_approval | upper) (substr 1 (len $upgrade_approval) $upgrade_approval) {{ "-hub}}" }}'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-devspaces-operator-uninstall
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/dev-spaces'
              operator: In
              values:
              - 'false'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-devspaces-operator-uninstall
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-devspaces-operator-uninstall
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-devspaces-operator-uninstall
    apiGroup: policy.open-cluster-management.io
    kind: Policy
