---
# Source: rhdh/templates/policy-developer-hub-operator-install.yaml
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-developer-hub-operator-install
  namespace: open-cluster-policies
spec:
  clusterSets:
    - hub
    - managed
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
# Source: rhdh/templates/policy-developer-hub-operator-install.yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-developer-hub-operator-install
  namespace: open-cluster-policies
placementRef:
  name: placement-policy-developer-hub-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-developer-hub-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
# Source: rhdh/templates/policy-developer-hub-operator-install.yaml
# This policy verifies the installation of the official & supported version of
# the Developer Hub Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
# Note that OpenShift 4.6 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-developer-hub-operator-install
  namespace: open-cluster-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: developer-hub-operator-ns
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: rhdh-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator-developer-hub
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: rhdh-operator-bcsvc
            namespace: rhdh-operator
          subscription:
            name: rhdh
            namespace: rhdh-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            channel: fast
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: developer-hub-operator-status
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: rhdh-operator
                spec:
                  displayName: 'Red Hat Developer Hub Operator'                
                status:
                  phase: Succeeded # check the csv status to determine if operator is running or not
