apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
 name: devspaces-install
 namespace: policies
spec:
 remediationAction: enforce
 disabled: false
 policy-templates:
   - objectDefinition:
       apiVersion: operators.coreos.com/v1alpha1
       kind: Subscription
       metadata:
         name: devspaces
         namespace: openshift-operators
       spec:
         channel: stable
         installPlanApproval: Automatic
         name: devspaces
         source: redhat-operators
         sourceNamespace: openshift-marketplace
