kind: Namespace
apiVersion: v1
metadata:
  name: stackrox
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    openshift.io/cluster-monitoring: "true"