{{- range $clusterSet, $value := .Values.clusterSets }}
{{- range $team, $teamjson := .Values.teams }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ $clusterSet }}
  namespace: openshift-gitops-{{ $team }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  clusterSet: {{ $clusterSet }}
{{- end }}
{{- end }}