{{- range $team := .Values.teams | default list "dev" }}
---
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: openshift-gitops-{{ $team }}
{{- end -}}