{{- range $team := .Values.teams | default list "dev" }}
---
apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollout
  namespace: openshift-gitops-{{ $team }}
  labels:
    example: basic
spec: {}
{{- end }}