# Default values for infra-nodes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
infraNodes:
  labelPrefix: "autoshift.io/"
  remediationAction: "inform"
  clusterSets:
    - hub
    - managed
  imageRegistry: 
    migrate: true
    remediationAction: enforce
  ingress: 
    migrate: true
    remediationAction: enforce
  monitoring: 
    migrate: true
    remediationAction: enforce
    removeConfig.yaml: |+
      alertmanagerMain:
        nodeSelector: {}
        tolerations: []
      prometheusK8s:
        nodeSelector: {}
        tolerations: []
      prometheusOperator:
        nodeSelector: {}
        tolerations: []
      k8sPrometheusAdapter:
        nodeSelector: {}
        tolerations: []
      kubeStateMetrics:
        nodeSelector: {}
        tolerations: []
      telemeterClient:
        nodeSelector: {}
        tolerations: []
      openshiftStateMetrics:
        nodeSelector: {}
        tolerations: []
      thanosQuerier:
        nodeSelector: {}
        tolerations: []
      monitoringPlugin:
        nodeSelector: {}
        tolerations: []
  gitops: 
    migrate: true
    remediationAction: enforce
    namespace: openshift-gitops
    apiVersion: pipelines.openshift.io/v1alpha1
    kind: GitopsService
    metadata:
      name: cluster
  zones:
    - us-east-2a
  externalIngress:
    clusterSets:
      - managed  
  dependencies: 
    install: 
      - "policy-infra-nodes"
    remove: 
      - policy-remove-infra-gitops 
      - policy-remove-infra-image-registry
      - policy-remove-infra-ingress
      - policy-remove-infra-monitoring 

