# Default values for infra-nodes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
infraNodes:
  labelPrefix: "autoshift.io/"
  remediationAction: "enforce"
  imageRegistry: 
    migrate: true
    remediationAction: enforce
  ingress: 
    migrate: true
    remediationAction: enforce
  monitoring: 
    migrate: true
    remediationAction: enforce
  gitops: 
    migrate: true
    remediationAction: enforce
    namespace: openshift-gitops
    apiVersion: pipelines.openshift.io/v1alpha1
    kind: GitopsService
    metadata:
      name: cluster
  externalIngress:
    clusterSets:
      - managed  
  dependencies: 
    install: 
      - "policy-infra-nodes-test"
    remove: 
      - policy-remove-infra-gitops 
      - policy-remove-infra-image-registry
      - policy-remove-infra-ingress
      - policy-remove-infra-monitoring 

