{{ if not (.Values.selfManaged | default false) }}
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: "local-cluster"
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResources=true"
  labels: {{ ((index (.Values.clusterSets) (.Values.hubClusterSet)).labels | toYaml) | nindent 4 }}
---
{{ end }}