{{- range $cluster, $data := .Values.clusters }}
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ printf "ManagedCluster-%s" $cluster }}
  namespace: "open-cluster-management" 
data: |+ 
  {{ $data | toYaml }}
{{- end }}


# Might need to use lookup instead, not sure if you can just hit the top level of the config map or if it requires a specific sub-field

