{{- if not (.Values.self-managed | default false) }}
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: "local-cluster"
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResources=true"
#  labels:
#    {{- range $index, $item := .Values.hubCluster.clusterlabels }}
#    {{ $item.name }}: {{ ($item.value | quote) | default "" }}
#    {{- end }}
---
{{- end }}


{{- if ne ((fromConfigMap "open-cluster-policies" .ManagedCluster).labels | default "") "" }}
  {{- range $label, $value := (fromConfigMap "open-cluster-policies" .ManagedCluster).labels }}
  {{- end }}
{{- end }}