{{ range $cluster, $data := .Values.clusters }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: "{{ printf "managed-cluster.%s" $cluster }}"
  namespace: "open-cluster-management" 
data: 
  values: | 
  {{ $data | toYaml | nindent 4 | trim }}
{{ end }}
{{ range $clusterSet, $data := .Values.clusterSets }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ printf "ClusterSet-%s" $clusterSet }}
  namespace: "open-cluster-management" 
data: {{ $data | toYaml | nindent 2 }}
{{ end }}