{{ range $cluster, $data := .Values.clusters }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: "{{ printf "ManagedCluster-%s" $cluster }}"
  namespace: "open-cluster-management" 
data: {{ $data | toJson }}
{{ end }}
{{ range $clusterSet, $data := .Values.clusterSets }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ printf "ClusterSet-%s" $clusterSet }}
  namespace: "open-cluster-management" 
data: {{ "'" }}{{ $data | toJson }}{{ "'" }}
{{ end }}