{{ range $cluster, $data := .Values.clusters }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: "{{ printf "managed-cluster.%s" $cluster }}"
  namespace: "open-cluster-management" 
data: 
  values: '{{ $data | toJson }}'
{{ end }}
{{ range $clusterSet, $data := .Values.clusterSets }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ printf "cluster-set.%s" $clusterSet }}
  namespace: "open-cluster-management" 
data:
  values: '{{ $data | toJson }}'
{{ end }}