# This policy verifies the installation of the official & supported version of
# the Compliance Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
# Note that OpenShift 4.6 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-logging-install
  namespace: open-cluster-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  dependencies:
    - name: policy-logging-operator-install
      namespace: open-cluster-policies
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
    - name: policy-loki-stack-install
      namespace: open-cluster-policies
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy    
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-install
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: logging.openshift.io/v1
                kind: ClusterLogging
                metadata:
                  name: instance 
                  namespace: openshift-logging
                spec:
                  collection:
                    type: vector
                  logStore:
                    lokistack:
                      name: logging-lokistack
                    retentionPolicy:
                      application:
                        maxAge: 7d
                      audit:
                        maxAge: 7d
                      infra:
                        maxAge: 7d
                    type: lokistack
                  visualization:
                    type: ocp-console
                    ocpConsole:
                      logsLimit: 15
                  managementState: Managed
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-logging-install
  namespace: open-cluster-policies
spec:
  clusterSets:
  {{- range .Values.logging.clusterSets }}
    - {{ . }}
  {{- end }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-logging-install
  namespace: open-cluster-policies
placementRef:
  name: placement-policy-logging-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-logging-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
