apiVersion: v1
kind: ConfigMap
metadata:
  name: aap-cr-config
  namespace: "{{ .Values.aap.namespace }}"
data:
  aap-cr.yaml: |
    apiVersion: aap.ansible.com/v1alpha1
    kind: AnsibleAutomationPlatform
    metadata:
      name: "{{ .Values.aap.instance }}"
      namespace: "{{ .Values.aap.namespace }}"
    spec:
      image_pull_policy: IfNotPresent
      controller:
        disabled: false
      hub:
        disabled: false
        storage_type: file
        file_storage_storage_class: "{{ .Values.aap.storage }}"
        file_storage_size: 10Gi
      lightspeed:
        disabled: true
