apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-aap-instance
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  dependencies:
    - name: policy-aap-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-instance
          namespace: policies-autoshift
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: aap.ansible.com/v1alpha1
                kind: AnsibleAutomationPlatform
                metadata:
                  name: "{{ .Values.aap.instance }}"
                  namespace: "{{ .Values.aap.namespace }}"
                spec:
                  controller:
                    disabled: false
                  hub:
                    disabled: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-hub-disabled" | default "false" hub{{ "}}" }}'
                    storage_type: file
                    file_storage_size: 10Gi
                    file_storage_storage_class: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-hub-storage-class" | default "{{ .Values.aap.storageClass }}" hub{{ "}}" }}'
                  lightspeed:
                    disabled: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-lightspeed-disabled" | default "true" hub{{ "}}" }}'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-aap-instance
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/metallb'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-aap-instance
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-aap-instance
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-aap-instance
    apiGroup: policy.open-cluster-management.io
    kind: Policy
