apiVersion: v1
kind: ServiceAccount
metadata:
  name: aap-creator
  namespace: ansible-automation-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aap-installer
  namespace: ansible-automation-platform
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["aap.ansible.com"]
    resources: ["ansibleautomationplatforms"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-aap-installer
  namespace: ansible-automation-platform
subjects:
  - kind: ServiceAccount
    name: aap-creator
    namespace: ansible-automation-platform
roleRef:
  kind: Role
  name: aap-installer
  apiGroup: rbac.authorization.k8s.io
