# Default values for loki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
odf:
    name: odf-operator
    namespace: openshift-storage
    channel: stable-4.17
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
hubClusterSets:
  hub:
    labels:
      test1: 'test'
managedClusterSets:
  managed:
    labels:
      test4: 'test'

# Labels
# autoshift.io/odf<bool>: If not set OpenShift Data Foundation will not be managed. if Storage Nodes are enable will deploy ODF on local storage/ storage nodes
# autoshift.io/odf-multi-cloud-gateway<String>: example standalone. Install ODF with only nooba object gateway or full odf
# autoshift.io/odf-channel<String>: default stable-4.17
# autoshift.io/odf-installPlanApproval<String>: default Automatic
# autoshift.io/odf-source<String>: default redhat-operators
# autoshift.io/odf-sourceNamespace<String>: default openshift-marketplace